### ISSUE TITLE
Improperly labeling two NeurIPS workshop papers

### ISSUE THREAD

**Issue by Happy2Git** [tamlhp/awesome-machine-unlearning#10]
- [SSSE: Efficiently Erasing Samples from Trained Machine Learning Models](https://openreview.net/forum?id=GRMKEx3kEo) is accepted by NeurIPS 2021 Workshop PRIML
- [Hidden Poison: Machine Unlearning Enables Camouflaged Poisoning Attacks](https://arxiv.org/abs/2212.10717) is accepted by NeurIPS 2022 Workshop Trustworthy and Socially Responsible Machine Learning

They are listed as main conference papers of NeurIPS, while they were actually accepted as workshop papers. This erroneous classification may cause ambiguity and confusion, leading to inaccurate attribution and citation for the authors and readers of these papers.

**Comment by Happy2Git** [comment]
The [sortable version](https://awesome-machine-unlearning.github.io/)  also miscategorises both papers.

**Comment by tamlhp** [comment]
Many thanks, we will update the first one as NeurIPS-PRIML and the second one as NeurIPS-TSRML. Hopefully it is ok.

**Comment by adasken** [comment]
Thank you for your suggestion. Changes are made in both repo and sortable version.
