### ISSUE TITLE
NIPS'23 accept paper

### ISSUE THREAD

**Issue by richhh520** [tamlhp/awesome-machine-unlearning#16]
Dear tamlhp,

Our paper Fast Model DeBias with Machine Unlearning has been accepted by NIPS'23. Here is the link: 
https://openreview.net/forum?id=BL9Pc7xsdX&noteId=BL9Pc7xsdX

We will appreciate it if you could update this paper.

Thanks,
Ruizhe

**Comment by adasken** [comment]
Thank you for your contribution, paper added
