### ISSUE TITLE
Accepted papers about Machine Unlearning in 2023

### ISSUE THREAD

**Issue by tamlhp** [tamlhp/awesome-machine-unlearning#18]
FairSISA: Ensemble Post-Processing to Improve Fairness of Unlearning in LLMs
https://arxiv.org/abs/2312.07420
https://research.ibm.com/publications/fairsisa-ensemble-post-processing-to-improve-fairness-of-unlearning-in-llms

**Comment by adasken** [comment]
Thank you, paper added
