### ISSUE TITLE
Adding some more resources

### ISSUE THREAD

**Issue by meg-huggingface** [tamlhp/awesome-machine-unlearning#2]
https://arxiv.org/abs/2003.10933 "Learn to Forget: Machine Unlearning via Neuron Masking", I believe would fit under "Model-Agnostic Approaches".
It also comes with another evaluation metric called "FORSAKEN".

**Comment by meg-huggingface** [comment]
https://arxiv.org/abs/2206.06520 "Memory-Based Model Editing at Scale" is also relevant (neural-network specific)

**Comment by adasken** [comment]
Thank you for the suggestion, we will review and update accordingly.

**Comment by meg-huggingface** [comment]
https://arxiv.org/abs/2205.10770 "Memorization Without Overfitting: Analyzing the Training Dynamics of Large Language Models" is LM-specific, but is potentially useful as a Survey.

**Comment by meg-huggingface** [comment]
Slightly tangential, since this is more about concepts than directly learned facts, but still relevant just in case you want to add:
https://arxiv.org/abs/2004.07667 ,  "Null It Out: Guarding Protected Attributes by Iterative Nullspace Projection"
