### ISSUE TITLE
arXiv papers about machine unlearning

### ISSUE THREAD

**Issue by tamlhp** [tamlhp/awesome-machine-unlearning#20]
Fast-NTK: Parameter-Efficient Unlearning for Large-Scale Models
https://arxiv.org/abs/2312.14923

**Comment by tamlhp** [comment]
FAST: Feature Aware Similarity Thresholding for Weak Unlearning in Black-Box Generative Models
https://arxiv.org/abs/2312.14895

**Comment by tamlhp** [comment]
Layer Attack Unlearning: Fast and Accurate Machine Unlearning via Layer Level Attack and Knowledge Distillation
https://arxiv.org/abs/2312.16823

**Comment by adasken** [comment]
Papers added.
