### ISSUE TITLE
AAAI 2024  accepted unlearning papers

### ISSUE THREAD

**Issue by if-loops** [tamlhp/awesome-machine-unlearning#21]
- [Separate the Wheat from the Chaff: Model Deficiency Unlearning via Parameter-Efficient Module Operation](https://arxiv.org/abs/2308.08090)
- [Learning to Unlearn: Instance-Wise Unlearning for Pre-trained Classifiers](https://arxiv.org/abs/2301.11578)
- [Fast Machine Unlearning without Retraining through Selective Synaptic Dampening](https://arxiv.org/abs/2308.07707)
- Towards Effective and General Graph Unlearning via Mutual Evolution (no  ArXiv link found)
- Backdoor Attacks via Machine Unlearning (no  ArXiv link found)

Source: https://aaai.org/wp-content/uploads/2024/01/AAAI_Main-Track_2024-01-04.pdf

**Comment by adasken** [comment]
Thank you for your suggestion! Papers added!

**Comment by tamlhp** [comment]
Thanks @if-loops, the arXiv link of "Towards Effective and General Graph Unlearning via Mutual Evolution" can be found here: https://arxiv.org/abs/2401.11760
