### ISSUE TITLE
A Survey Paper on Federated Unlearning

### ISSUE THREAD

**Issue by tamlhp** [tamlhp/awesome-machine-unlearning#24]
Federated Unlearning: A Survey on Methods, Design Guidelines, and Evaluation Metrics
https://arxiv.org/abs/2401.05146

**Comment by tamlhp** [comment]
SoK: Challenges and Opportunities in Federated Unlearning
https://arxiv.org/abs/2403.02437

**Comment by adasken** [comment]
Two surveys added.
