### ISSUE TITLE
New arXiv paper(s) on machine unlearning

### ISSUE THREAD

**Issue by tamlhp** [tamlhp/awesome-machine-unlearning#29]
Corrective Machine Unlearning
https://arxiv.org/abs/2402.14015
(This paper studies the interplay between adversarial attacks and machine unlearning).

**Comment by tamlhp** [comment]
Decentralized Federated Unlearning on Blockchain
https://arxiv.org/abs/2402.16294

**Comment by tamlhp** [comment]
Towards Efficient and Effective Unlearning of Large Language Models for Recommendation
https://arxiv.org/abs/2403.03536
(Machine Unlearning + LLM + Recommender Systems)

**Comment by tamlhp** [comment]
Challenging Forgets: Unveiling the Worst-Case Forget Sets in Machine Unlearning
https://arxiv.org/abs/2403.07362

**Comment by tamlhp** [comment]
Towards Independence Criterion in Machine Unlearning of Features and Labels
https://arxiv.org/abs/2403.08124

**Comment by tamlhp** [comment]
∇τ : Gradient-based and Task-Agnostic machine Unlearning
https://arxiv.org/abs/2403.14339

**Comment by tamlhp** [comment]
Unlearning Backdoor Threats: Enhancing Backdoor Defense in Multimodal Contrastive Learning via Local Token Unlearning
https://arxiv.org/abs/2403.16257

**Comment by tamlhp** [comment]
CovarNav: Machine Unlearning via Model Inversion and Covariance Navigation
https://arxiv.org/abs/2311.12999

**Comment by tamlhp** [comment]
Making Users Indistinguishable: Attribute-wise Unlearning in Recommender Systems
https://arxiv.org/abs/2310.05847

Post-Training Attribute Unlearning in Recommender Systems
https://arxiv.org/abs/2403.06737

**Comment by adasken** [comment]
Papers added
