### ISSUE TITLE
New paper on Unlearning

### ISSUE THREAD

**Issue by Rishav1** [tamlhp/awesome-machine-unlearning#3]
https://arxiv.org/pdf/2210.08911.pdf "Forget Unlearning: Towards True Data Deletion in Machine Learning." This paper identifies major flaws in the definition of standard machine unlearning guarantees and fixes them in a new data deletion definition. It also proves that DP-GD is an optimal data-deletion algorithm for convex and nearly optimal for non-convex losses.

**Comment by adasken** [comment]
Thank you for the suggestion. We will review and update.
