### ISSUE TITLE
Corrective Unlearning missing info in Entry

### ISSUE THREAD

**Issue by shash42** [tamlhp/awesome-machine-unlearning#39]
The entry for our paper Corrective Machine Unlearning has the following issues:
1. It misspells author name, it should be Goel et al. not Geol et al.
2. Codebase: https://github.com/drimpossible/corrective-unlearning-bench
3. It was accepted to ICLR DMLR Workshop 2024

Please fix these thanks!

**Comment by tamlhp** [comment]
Many thanks, we have updated the information. Please kindly let us know if there is any problem.
