### ISSUE TITLE
Need a sortable table of existing approaches.

### ISSUE THREAD

**Issue by kvt0012** [tamlhp/awesome-machine-unlearning#4]
Hello everyone, 
The current version is not sortable. It is quite difficult to find recent papers in a chronological order.
Can you give me any advice? 
Best regards,
Thank you

**Comment by tamlhp** [comment]
Thanks a lot for your suggestions. We have created a website to make it easier to search and sort the machine unlearning literature. https://awesome-machine-unlearning.github.io/
