### ISSUE TITLE
New paper(s) about federated unlearning

### ISSUE THREAD

**Issue by tamlhp** [tamlhp/awesome-machine-unlearning#40]
Federated Unlearning: a Perspective of Stability and Fairness
https://arxiv.org/abs/2402.01276

**Comment by QQQHY** [comment]
FedCIO: Efficient Exact Federated Unlearning with Clustering, Isolation, and One-shot Aggregation
https://ieeexplore.ieee.org/document/10386788

**Comment by tamlhp** [comment]
Papers are included in this repos and our survey paper.
