### ISSUE TITLE
New paper(s) on machine unlearning

### ISSUE THREAD

**Issue by ZFancy** [tamlhp/awesome-machine-unlearning#46]
1. mismatched machine unlearning
Title: Decoupling the Class Label and the Target Concept in Machine Unlearning
arXiv: https://arxiv.org/abs/2406.08288

2. evaluation of LLM unlearning
Title: Unlearning with Control: Assessing Real-world Utility for Large Language Model Unlearning
arXiv: https://arxiv.org/abs/2406.09179

Thanks if you would consider adding them to this repo!

**Comment by tamlhp** [comment]
Many thanks Jianing, we will check and add them soon. Thank you very much for your contribution.

**Comment by tamlhp** [comment]
The two papers have been included in the repos and our survey paper.
