### ISSUE TITLE
Please add this ECCV2024 accepted paper

### ISSUE THREAD

**Issue by jbonato1** [tamlhp/awesome-machine-unlearning#49]
Scope: Model agnostic machine Unlearning , No retain dataset used (Zero-shot)
Title: Is Retain Set All You Need in Machine Unlearning? Restoring Performance of Unlearned Models with Out-Of-Distribution Images
link https://arxiv.org/abs/2404.12922

**Comment by tamlhp** [comment]
Could you please kindly let us know how to cite (e.g. bibtex) your ECCV paper version (https://eccv.ecva.net/virtual/2024/poster/1578). Or would you prefer to add the arxiv version?

**Comment by jbonato1** [comment]
Hi thanks for your message. The arxiv version is fine.
Regards 
Jacopo

**Comment by tamlhp** [comment]
Incorporated in the repos and our survey paper
