### ISSUE TITLE
Please add this paper: Towards Adversarial Evaluations of Inexact Unlearning

### ISSUE THREAD

**Issue by shash42** [tamlhp/awesome-machine-unlearning#5]
ArXiv: https://arxiv.org/abs/2201.06640
Code: https://github.com/shash42/Evaluating-Inexact-Unlearning

Proposes an evaluation method: the Interclass Confusion Test
Proposes 2 baseline methods: EU-k, CF-k
Theoretical Discussion of various phenomenon in unlearning

**Comment by adasken** [comment]
Thank you, we have added the paper.
