### ISSUE TITLE
[New paper on Usenix Security] Inductive Graph Unlearning

### ISSUE THREAD

**Issue by Happy2Git** [tamlhp/awesome-machine-unlearning#8]
Hi, please add this new paper: Inductive Graph Unlearning (https://arxiv.org/abs/2304.03093) with code: https://github.com/Happy2Git/GUIDE. This paper has been accepted by Usenix Security'23.

**Comment by Happy2Git** [comment]
@tamlhp Hi, could you please add this paper? It's new.

**Comment by tamlhp** [comment]
Many thanks for your contribution. We will add it promptly. Sorry we had to catch some deadlines last week.

**Comment by adasken** [comment]
Thank you for your contribution @Happy2Git. Paper added.
