### ISSUE TITLE
[New paper of unlearning] - Heterogeneous Federated Knowledge Graph Embedding Learning and Unlearning

### ISSUE THREAD

**Issue by ZhuYuqicheng** [tamlhp/awesome-machine-unlearning#9]
I found following paper related to unlearning: https://arxiv.org/abs/2302.02069, it deals with unlearning knowledge from local clients in federated KGE setting. :)

**Comment by tamlhp** [comment]
Many thanks, Yuqicheng. Yes, very interesting paper from WWW 2023. We will add it into the repos and the paper soon.

**Comment by adasken** [comment]
Thank you @ZhuYuqicheng for your suggestion. Paper added.
